### PR TITLE
Work around missing --allow_natives_syntax

### LINKED ISSUE #14: Broken on Node.js 8, 9, and Master
Different reasons for each one (compounding)

8.x: 
```
it can load native_module and module
  not ok TypeError: require(...).internalBinding is not a function
```

9.x:
```
it can load native_module and module
not ok ReferenceError: internalBinding is not defined
```

master:
```
test/basic.js ......................................... 4/7
  it can load native_module and module
  not ok SyntaxError: Unexpected token %
    stack: |
      SyntaxError: Unexpected token %
          runInThisContext (index.js:2:206)
          req_ (index.js:13:1586)
          require (index.js:13:1162)
          util.js:29:52
          req_ (index.js:13:1762)
          require (index.js:13:1162)
          module.js:25:14
          req_ (index.js:13:1762)
          Object.req [as require] (index.js:9:302)
          test/basic.js:34:11
    test: it can load native_module and module
    message: 'SyntaxError: Unexpected token %'

  fs is like fs but not fs
  not ok SyntaxError: Unexpected token %
    stack: |
      SyntaxError: Unexpected token %
          runInThisContext (index.js:2:206)
          req_ (index.js:13:1586)
          require (index.js:13:1162)
          util.js:29:52
          req_ (index.js:13:1762)
          require (index.js:13:1162)
          fs.js:29:14
          req_ (index.js:13:1762)
          Object.req [as require] (index.js:9:302)
          test/basic.js:46:21
    test: fs is like fs but not fs
    message: 'SyntaxError: Unexpected token %'

  support a whitelist
  not ok SyntaxError: Unexpected token %
    stack: |
      SyntaxError: Unexpected token %
          runInThisContext (index.js:2:206)
          req_ (index.js:13:1586)
          require (index.js:13:1162)
          util.js:29:52
          req_ (index.js:13:1762)
          require (index.js:13:1162)
          fs.js:29:14
          req_ (index.js:13:1762)
          Object.req [as require] (index.js:9:302)
          test/basic.js:60:20
    test: support a whitelist
    message: 'SyntaxError: Unexpected token %'

total ................................................. 4/7
```

I'm digging into the bugs regarding internalBinding, in the mean time it looks like the other breakages on master are due to https://github.com/nodejs/node/pull/13295

Will see if I can come up with a patch

### PR DESCRIPTION
**Pull request by addaleax**
Fixes: https://github.com/isaacs/natives/issues/14

@isaacs This *does* fix gulp, fwiw.

Also, if it helps & you’re interested, I can help with maintenance of this module for as long as gulp is on graceful-fs@3

### CODE REVIEW

**Comment by isaacs** [comment]
@addaleax I'm happy to transfer this module entirely to you, and also direct all graceful-fs@3 complaints/requests your way, if you're interested :)

**Comment by addaleax** [comment]
> I'm happy to transfer this module entirely to you

@isaacs I see it as something that somebody just might have to do. ;)

> and also direct all graceful-fs@3 complaints/requests your way, if you're interested

Okay, my time is *somewhat* limited but you should always feel free to ping me in any issues in which you think I’d be a good person to provide assistance!

**Comment by isaacs** [comment]
Landed in master, pushed to v1.1.1

I also made you the only publisher on npm

```
$ npm owner ls natives
addaleax <anna@addaleax.net>
```

If you delete your fork, I'll transfer the main repo to you.  Or if you'd prefer it go to an org somewhere, that's fine, too.

/me tosses hot potato in Anna's direction, runs hands under some cold water

**Comment by addaleax** [comment]
> If you delete your fork, I'll transfer the main repo to you.

Done! I think this is the first time I’ve ever deleted a repo. 😄

**Pull request closed without merging**
